apiVersion: v1
kind: ReplicationController
metadata:
  name: "bob"
spec:
  replicas: 1
  selector:
    app: nginx
  templates:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
    containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
